runtime_cfg:
  mode: local
  host: "127.0.0.1"
  port: 8080
  open_browser: false
  render_mode: client
  offscreen: true
  verbose: false
  still_ratio: 1.0
  interactive_ratio: 1.0
  aa: ssaa
  multi_samples: 2
scene_cfg:
  data_dir: /home/niklas/PSI/cmecme/cmecme_poly_part1_run1a_cme/cor_mhd
  t0: 01/01/1990 00:00:00
  time_file: mas_dumps_3d.txt
  tracer_header: tracer_header.dat
  tracer_prefix: tracers_pos
  lp_prefix: lp_
  bg_lp: null
  label_select:
  - apex
  - axis
  - arcade
  - ring_lp_03
  - ring_lp_05
  - ring_lp_07
  - ring_lp_09
  - ring_lp_11
  - ring_lp_13
  - ring_lp_15
  - ring_lp_17
  - background
  max_traces: 50
  max_steps: 500
