mode: local
host: 127.0.0.1
open_browser: true
render_mode: client
offscreen: false
port: 8080
verbose: false
max_steps: 500
cme_directory: /home/niklas/PSI/cme-viewer/dat/cmecme/cmecme_poly_part1_run1a_cme/cor_mhd
time_stamps: mas_dumps_3d.txt
t0: null
tracer_header: tracer_header.dat
tracer_prefix: tracers_pos
launch_point_prefix: null
max_traces: 70
label_select: fr1_apex,fr1_arcade,fr1_axis,fr2_apex,fr2_arcade,fr2_axis
bg_lp: null
